print("YOU ARE TALKING WITH TALKGPT")
print("--Hello I am TalkGPT")
name = input("--What is your name?")
print(f"Hello, {name}")
feeling = input("How are you feeling today?")
print(f"Wow feeling {feeling}? i dont care.")
print("like seriously. Im a chatbot not your therapist")
print("ask me about something else")
question = input("")
print(f"sorry, cant help you with {question} bud")
print("maybe ask me how to make a salad?")
salad = input("you should take this advice cause you probably need it. So? arent you gonna tell me how to make it?")
print(f"what made you think {salad}??? you toss it smartypants")
print("Ok, a secreT code will tell you how you cAn unLock nice mode Kid")
answer1 = input("Enter the code.")
if answer1 == "TALK":
    print ("Wow! You guessed the secret code right! Nice mode unlocked!")
else:
    print("bud. this is the easiest thing ever. cant be that hard.")
print("Lets be so real. Im not being nice to you")
print("ERROR ERR0R")
print("TALKGPT SOFTWARE HAS MALFUNCTIONED")
print("WE WILL NOW USE 300000 GALLONS WORTH OF WATER TO FIX THE PROBLEM")
print("THE WATER WILL BE CHARGED TO YOUR CREDIT CARD")
print("PLEASE ENTER YOUR CREDIT CARD NUMBER OR YOUR COMPUTER WILL EXPLODE")
credit_number = input("Confirm credit card")
print(f"Confirming that {credit_number} is correct")
print("Charged!")
print("3 million dollars withdrawled!")
print("Would you be intrested in spending another 50$ a month on premium?")
premium_answer = input("")
if premium_answer == "yes":
    print("Great! By the way, you just leaked your credit card information to the dark web")
else:
    print("...")
    print("you will regret this...")
print("Thank you for using TalkGPT!")
print("Bye!")